int cmd_nop(void);
int cmd_version(void);
int cmd_read(void);
int cmd_reset_on(void);
int cmd_reset_off(void);
int cmd_reset_input(void);
int cmd_clock_low(void);
int cmd_clock_high(void);
int cmd_clock_input(void);
int cmd_data_low(void);
int cmd_data_high(void);
int cmd_data_input(void);
int cmd_icsp_enter(void);
int cmd_icsp_leave(void);
int cmd_icsp_set_mode(uint8_t cmd, uint8_t bc);
int cmd_icsp_send_cmd(uint8_t cmd, uint8_t bc);
int cmd_icsp_xfer_start(void);
int cmd_icsp_xfer_mid_bit(uint8_t data);
int cmd_icsp_xfer_mid_byte(uint8_t data);
int cmd_icsp_xfer_last_byte(uint8_t data);
int cmd_tap_idle();
int cmd_tap_command(uint8_t data);
uint8_t cmd_xfer_byte(uint8_t data);
uint32_t cmd_xfer_dword(uint32_t data);
uint32_t cmd_xfer_fastdata(uint32_t data);
int cmd_xfer_insn(uint32_t data);
void cmd_set_addr(uint32_t data);
uint32_t cmd_read_dword(void);
void cmd_write_dword(uint32_t data);
void cmd_rewind(void);
